version: '3.8'

services:
  postgres:
    build: ./postgres
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flask-app:
    build: ./flask
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask-app

volumes:
  pgdata:

