apiVersion: v1
kind: Service
metadata:
  name: npsvc
  namespace: tg
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32001
      name: https
  selector:
    env: stage

