apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: stage
  name: app2
  namespace: tg
spec:
  containers:
  - image: cdtsbikaner/project1:v.1.0.1
    name: c1
    ports:
      - containerPort: 8080
  - image: nginx
    name: c2
    ports:
      - containerPort: 80
