apiVersion: v1
kind: Pod
metadata:
  name: dbtoleration-app-new
  namespace: tg
spec:
  containers:
   - name: c1
     image:  mysql:5.7
     env:
       - name: MYSQL_ROOT_PASSWORD
         value: redhat
     ports:
       - containerPort: 3306 
  tolerations:
   - key: wn1
     operator: Equal
     value: database
     effect: NoSchedule
